project:
  type: website
  output-dir: docs

website:
  title: "Kavindu Piyumal"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/kavindu99
format:
  html:
    theme: solar
    css: styles.css



